# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "wallet_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "wallet_password") %>


development:
  <<: *default
  database: wallet_api_development

test:
  <<: *default
  database: wallet_api_test

production:
  <<: *default
  database: wallet_api_production
